name: 自动构建docker镜像English

on:
  schedule:
    - cron: "21 19 * * 0"
  watch:
    types: started
  workflow_dispatch:

#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push i386 arm64 armv7
        id: docker_build_i386_arm64_armv7
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfile/
          file: ./dockerfile/Dockerfile_eng
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/zerotier:eng
          platforms: linux/386,linux/arm64,linux/arm
      - name: amd64 Image digest
        run: echo ${{ steps.docker_build_i386_arm64_armv7.outputs.digest }}
